name: clima
description:  Weather app -  find out the live weather data in the current location of the device as well as the weather for any city you can think of.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.4+2
  http: ^0.12.0+2
  flutter_spinkit: ^4.1.1+1
  rflutter_alert: ^1.0.3
  autocomplete_textfield: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900